import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright Configuration for HospoGo E2E Tests
 * 
 * Configured for Vercel/Firebase dev environments:
 * - Dev mode: Uses localhost:3000 with Firebase emulator/auth
 * - Production mode: Uses https://hospogo.com (set E2E_AUTH_MODE=production)
 * 
 * See https://playwright.dev/docs/test-configuration.
 */
const useProductionAuth = process.env.E2E_AUTH_MODE === 'production';
const baseURL = useProductionAuth
  ? 'https://hospogo.com'
  : 'http://localhost:3000';

export default defineConfig({
  testDir: './tests',
  /* Global setup - authenticate once before all tests */
  globalSetup: useProductionAuth ? undefined : './tests/auth.setup.ts',
  /* Run tests in files in parallel */
  fullyParallel: false, // Disabled to prevent Cursor/IDE disconnects during high-load browser runs
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Use multiple workers locally, single worker in CI to prevent Cursor/IDE disconnects during high-load browser runs */
  workers: process.env.CI ? 1 : undefined,
  /* Fail fast - stop after first failure */
  maxFailures: 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL,
    /* Load authenticated session state for all tests */
    /* Note: storageState.json is generated by tests/auth.setup.ts during globalSetup */
    /* It includes both localStorage and sessionStorage for E2E authentication */
    storageState: useProductionAuth ? 'playwright/.auth/user.json' : './tests/storageState.json',
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    /* Screenshot on failure */
    screenshot: 'only-on-failure',
  },
  /* Expect timeout configuration */
  expect: {
    timeout: 5000,
    /* Visual comparison settings for screenshot tests */
    toHaveScreenshot: {
      maxDiffPixelRatio: 0.05, // Allow 5% pixel difference for strict CSS enforcement
    },
  },

  /* Configure projects for major browsers */
  projects: useProductionAuth
    ? [
        { name: 'setup', testMatch: /.*\.prod\.setup\.ts/ },
        {
          name: 'chromium',
          use: {
            ...devices['Desktop Chrome'],
            storageState: 'playwright/.auth/user.json',
          },
          dependencies: ['setup'],
        },
        {
          name: 'Mobile Chrome',
          use: {
            ...devices['Pixel 5'],
            storageState: 'playwright/.auth/user.json',
            actionTimeout: 45000, // Increase action timeout for mobile
            navigationTimeout: 45000, // Increase navigation timeout for mobile
          },
          dependencies: ['setup'],
          retries: 2, // Retry mobile tests to handle server cold-starts
        },
        {
          name: 'Mobile Safari',
          use: {
            ...devices['iPhone 12'],
            navigationTimeout: 45000, // Increase timeout for Mobile Safari
            actionTimeout: 45000, // Increase action timeout for mobile
            storageState: 'playwright/.auth/user.json',
          },
          dependencies: ['setup'],
          retries: 2, // Retry mobile tests to handle server cold-starts
        },
      ]
    : [
        {
          name: 'chromium',
          use: { ...devices['Desktop Chrome'] },
        },
        {
          name: 'Mobile Chrome',
          use: { 
            ...devices['Pixel 5'],
            actionTimeout: 45000, // Increase action timeout for mobile
            navigationTimeout: 45000, // Increase navigation timeout for mobile
          },
          retries: 2, // Retry mobile tests to handle server cold-starts
        },
        {
          name: 'Mobile Safari',
          use: { 
            ...devices['iPhone 12'],
            navigationTimeout: 45000, // Increase timeout for Mobile Safari
            actionTimeout: 45000, // Increase action timeout for mobile
          },
          retries: 2, // Retry mobile tests to handle server cold-starts
        },
      ],

  /* Run your local dev server before starting the tests */
  webServer: useProductionAuth
    ? undefined
    : {
        command: 'npm run dev:all',
        url: 'http://localhost:3000',
        reuseExistingServer: !process.env.CI,
        timeout: 120 * 1000,
        stdout: 'pipe',
        stderr: 'pipe',
        env: {
          VITE_E2E: '1', // Disable tutorial overlay during E2E tests
          NODE_ENV: 'test', // Enable backend E2E authentication bypass
          // Note: The API server (port 5000) will receive NODE_ENV=test
          // via the env object above. Concurrently should pass env vars to child processes.
          // The backend middleware checks for process.env.NODE_ENV === 'test' to enable
          // test authentication bypass (see api/_src/middleware/auth.ts)
        },
        // Wait for both frontend and API to be ready
        // The frontend will be ready when localhost:3000 responds
        // We'll add a health check in the test setup to ensure API is also ready
      },
});
