# Development overrides for docker-compose
# This file is automatically merged with docker-compose.yml in development

version: '3.8'

services:
  # Development overrides for API service
  api:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for hot reloading
      - ./api/src:/app/src:cached
      - ./api/package.json:/app/package.json:cached
      - ./api/tsconfig.json:/app/tsconfig.json:cached
      # Don't mount node_modules for better performance
    command: ["npm", "run", "dev"]
    # Override health check for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Development overrides for Web service
  web:
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reloading
      - ./web:/app:cached
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    # Override health check for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Development database with persistent data
  postgres:
    environment:
      - POSTGRES_DB=snipshift_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Development Redis
  redis:
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
  redis_dev_data:
