import { format } from 'date-fns';
import { Loader2, UserPlus, Repeat, Clock } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';

export interface ShiftBlockProps {
  event: {
    id: string;
    title: string;
    start: Date;
    end: Date;
    resource?: {
      booking?: any;
      status?: 'draft' | 'invited' | 'confirmed' | 'pending' | 'completed' | 'past' | 'unassigned' | 'open' | 'OPEN' | 'PUBLISHED' | 'filled';
      type?: 'job' | 'shift' | 'auto-slot' | 'bucket';
      isAutoGenerated?: boolean;
    };
  };
  onClick?: () => void;
  isRecurring?: boolean;
  /** Optional className to override or extend default styles */
  className?: string;
}

/** Normalize assignedStaff to array (supports legacy single object). */
function toAssignedList(val: unknown): Array<{ id?: string; name?: string; displayName?: string; avatarUrl?: string }> {
  if (Array.isArray(val)) return val.filter(Boolean);
  if (val && typeof val === 'object') return [val as any];
  return [];
}

/**
 * Get a clean, short display name for the shift
 * Prioritizes showing time range or simple label over long names
 */
function getShiftLabel(event: ShiftBlockProps['event']): string {
  // Try to get the time range as a compact label
  try {
    const startTime = format(event.start, 'h:mma').toLowerCase();
    return `${startTime}`;
  } catch {
    // Fallback to a simple label based on time of day
    const hour = event.start.getHours();
    if (hour < 12) return 'Morning';
    if (hour < 17) return 'Afternoon';
    return 'Evening';
  }
}

/**
 * ShiftBlock Component
 * Renders a shift event block with different states:
 * - UNASSIGNED: Clean amber/yellow block with time
 * - CONFIRMED: Green block with staff name
 * - INVITED: Orange with pending indicator
 * 
 * Optimized for month view readability with minimal clutter
 */
export function ShiftBlock({ event, onClick, isRecurring, className }: ShiftBlockProps) {
  const status = event.resource?.status || 'draft';
  const shift = event.resource?.booking?.shift || event.resource?.booking?.job;
  const rawAssigned = shift?.assignedStaff ?? shift?.assignments ?? shift?.professional;
  const assignedList = toAssignedList(rawAssigned);
  const capacity = Math.max(1, (shift?.capacity ?? 1) as number);
  const filled = assignedList.length;
  const showRecurring = isRecurring || shift?.isRecurring || shift?.recurringSeriesId;
  const isAutoGenerated = event.resource?.isAutoGenerated;
  const isUnassigned = status === 'unassigned' && isAutoGenerated;
  const hasSlots = capacity > filled;

  const shiftLabel = getShiftLabel(event);

  // Handle click with proper event handling
  const handleClick = (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent event bubbling
    if (onClick) {
      onClick();
    }
  };

  // State A: UNASSIGNED (Auto-generated slot) - Clean amber style, no dashed border
  if (isUnassigned) {
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-unassigned-slot"
        className={cn(
          "shift-block shift-block-unassigned",
          "w-full h-full rounded-md",
          "bg-amber-500/90 dark:bg-amber-600/90 cursor-pointer",
          "flex items-center gap-1.5 px-2 py-1",
          "hover:bg-amber-500 dark:hover:bg-amber-600 transition-colors",
          "text-white relative overflow-hidden",
          className
        )}
        style={{ minHeight: '22px' }}
      >
        <Clock className="h-3 w-3 flex-shrink-0 opacity-80" />
        <span className="text-xs font-medium truncate">{shiftLabel}</span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // State B: DRAFT (Ghost Slot) - Subtle outline style
  if (status === 'draft') {
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-ghost-slot"
        className={cn(
          "shift-block shift-block-draft",
          "w-full h-full rounded-md border",
          "bg-slate-100/50 dark:bg-slate-800/50 cursor-pointer",
          "border-slate-300 dark:border-slate-600",
          "flex items-center gap-1.5 px-2 py-1",
          "hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors",
          "text-slate-600 dark:text-slate-300 relative overflow-hidden",
          className
        )}
        style={{ minHeight: '22px' }}
      >
        <UserPlus className="h-3 w-3 flex-shrink-0 opacity-70" />
        <span className="text-xs font-medium truncate">Open</span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-60" />
        )}
      </div>
    );
  }

  // State C: INVITED (Pending) - Orange with subtle spinner
  if (status === 'invited') {
    const first = assignedList[0];
    const staffName = first?.name || first?.displayName || 'Pending';
    const firstName = staffName.split(' ')[0];

    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-pending"
        className={cn(
          "shift-block shift-block-invited",
          "w-full h-full rounded-md",
          "bg-orange-500/90 dark:bg-orange-600/90",
          "cursor-pointer hover:bg-orange-500 dark:hover:bg-orange-600 transition-colors",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
          className
        )}
        style={{ minHeight: '22px' }}
      >
        <Loader2 className="h-3 w-3 text-white/80 animate-spin flex-shrink-0" />
        <span className="text-white text-xs font-medium truncate flex-1">
          {capacity > 1 ? `${filled}/${capacity} Filled` : firstName}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-white absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // State D: PENDING/OPEN (Posted to Job Board) - Amber/Yellow; show 0/capacity when capacity > 1
  if (status === 'pending' || status === 'open' || status === 'OPEN' || status === 'PUBLISHED') {
    const openLabel = capacity > 1 ? `0/${capacity}` : shiftLabel;
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-open"
        className={cn(
          "shift-block shift-block-open",
          "w-full h-full rounded-md",
          "bg-amber-500/90 dark:bg-amber-600/90",
          "cursor-pointer hover:bg-amber-500 dark:hover:bg-amber-600 transition-colors",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
          className
        )}
        style={{ minHeight: '22px' }}
      >
        <Clock className="h-3 w-3 text-white flex-shrink-0 opacity-80" />
        <span className="text-white text-xs font-medium truncate flex-1">
          {openLabel}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-white absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // State E: CONFIRMED (Locked) - Green with staff avatars and/or "X/Y Filled", "Add Worker" when capacity > filled
  if (status === 'confirmed' || status === 'filled') {
    const avatarsToShow = assignedList.slice(0, 3);
    const first = assignedList[0];
    const firstName = (first?.name || first?.displayName || 'Confirmed').split(' ')[0];

    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-confirmed"
        className={cn(
          "shift-block shift-block-confirmed",
          "w-full h-full rounded-md",
          "bg-emerald-600 dark:bg-emerald-700",
          "cursor-pointer hover:bg-emerald-700 dark:hover:bg-emerald-800 transition-colors",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
          className
        )}
        style={{ minHeight: '22px' }}
      >
        <div className="flex items-center gap-0.5 flex-shrink-0">
          {avatarsToShow.map((s, i) => (
            <Avatar key={s?.id || i} className="h-4 w-4 border border-white/30">
              <AvatarImage src={(s as any)?.avatarUrl} />
              <AvatarFallback className="text-[8px] bg-white/20 text-white">
                {(s?.name || s?.displayName || '?').charAt(0).toUpperCase()}
              </AvatarFallback>
            </Avatar>
          ))}
          {hasSlots && (
            <div
              className="h-4 w-4 rounded-full border border-dashed border-white/60 flex items-center justify-center bg-white/10"
              title="Add Worker"
            >
              <UserPlus className="h-2.5 w-2.5 text-white/80" />
            </div>
          )}
        </div>
        <span className="text-white text-xs font-medium truncate flex-1">
          {capacity > 1 ? `${filled}/${capacity} Filled` : firstName}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-white absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // Fallback: Default rendering for other statuses (past, etc.)
  return (
    <div
      onClick={handleClick}
      className={cn(
        "shift-block shift-block-default",
        "w-full h-full rounded-md",
        "bg-slate-400/80 dark:bg-slate-600/80",
        "cursor-pointer hover:bg-slate-500 dark:hover:bg-slate-700 transition-colors",
        "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
        "text-white text-xs font-medium",
        className
      )}
      style={{ minHeight: '22px' }}
    >
      <span className="truncate">{shiftLabel}</span>
      {showRecurring && (
        <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-70" />
      )}
    </div>
  );
}

