import React from 'react';
import { format } from 'date-fns';
import { Loader2, UserPlus, Repeat, Clock } from 'lucide-react';
import { cn } from '@/lib/utils';

export interface ShiftBlockProps {
  event: {
    id: string;
    title: string;
    start: Date;
    end: Date;
    resource?: {
      booking?: any;
      status?: 'draft' | 'invited' | 'confirmed' | 'pending' | 'completed' | 'past' | 'unassigned';
      type?: 'job' | 'shift';
      isAutoGenerated?: boolean;
    };
  };
  onClick?: () => void;
  isRecurring?: boolean;
}

/**
 * Get a clean, short display name for the shift
 * Prioritizes showing time range or simple label over long names
 */
function getShiftLabel(event: ShiftBlockProps['event']): string {
  // Try to get the time range as a compact label
  try {
    const startTime = format(event.start, 'h:mma').toLowerCase();
    const endTime = format(event.end, 'h:mma').toLowerCase();
    return `${startTime}`;
  } catch {
    // Fallback to a simple label based on time of day
    const hour = event.start.getHours();
    if (hour < 12) return 'Morning';
    if (hour < 17) return 'Afternoon';
    return 'Evening';
  }
}

/**
 * ShiftBlock Component
 * Renders a shift event block with different states:
 * - UNASSIGNED: Clean amber/yellow block with time
 * - CONFIRMED: Green block with staff name
 * - INVITED: Orange with pending indicator
 * 
 * Optimized for month view readability with minimal clutter
 */
export function ShiftBlock({ event, onClick, isRecurring }: ShiftBlockProps) {
  const status = event.resource?.status || 'draft';
  const shift = event.resource?.booking?.shift || event.resource?.booking?.job;
  const assignedStaff = shift?.assignedStaff || shift?.professional;
  const showRecurring = isRecurring || shift?.isRecurring || shift?.recurringSeriesId;
  const isAutoGenerated = event.resource?.isAutoGenerated;
  const isUnassigned = status === 'unassigned' && isAutoGenerated;
  
  const shiftLabel = getShiftLabel(event);

  // Handle click with proper event handling
  const handleClick = (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent event bubbling
    if (onClick) {
      onClick();
    }
  };

  // State A: UNASSIGNED (Auto-generated slot) - Clean amber style, no dashed border
  if (isUnassigned) {
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-unassigned-slot"
        className={cn(
          "shift-block shift-block-unassigned",
          "w-full h-full rounded-md",
          "bg-amber-500/90 dark:bg-amber-600/90 cursor-pointer",
          "flex items-center gap-1.5 px-2 py-1",
          "hover:bg-amber-500 dark:hover:bg-amber-600 transition-colors",
          "text-white relative overflow-hidden"
        )}
        style={{ minHeight: '22px' }}
      >
        <Clock className="h-3 w-3 flex-shrink-0 opacity-80" />
        <span className="text-xs font-medium truncate">{shiftLabel}</span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // State B: DRAFT (Ghost Slot) - Subtle outline style
  if (status === 'draft') {
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-ghost-slot"
        className={cn(
          "shift-block shift-block-draft",
          "w-full h-full rounded-md border",
          "bg-slate-100/50 dark:bg-slate-800/50 cursor-pointer",
          "border-slate-300 dark:border-slate-600",
          "flex items-center gap-1.5 px-2 py-1",
          "hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors",
          "text-slate-600 dark:text-slate-300 relative overflow-hidden"
        )}
        style={{ minHeight: '22px' }}
      >
        <UserPlus className="h-3 w-3 flex-shrink-0 opacity-70" />
        <span className="text-xs font-medium truncate">Open</span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-60" />
        )}
      </div>
    );
  }

  // State C: INVITED (Pending) - Orange with subtle spinner
  if (status === 'invited') {
    const staffName = assignedStaff?.name || assignedStaff?.displayName || 'Pending';
    const firstName = staffName.split(' ')[0];

    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-pending"
        className={cn(
          "shift-block shift-block-invited",
          "w-full h-full rounded-md",
          "bg-orange-500/90 dark:bg-orange-600/90",
          "cursor-pointer hover:bg-orange-500 dark:hover:bg-orange-600 transition-colors",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden"
        )}
        style={{ minHeight: '22px' }}
      >
        <Loader2 className="h-3 w-3 text-white/80 animate-spin flex-shrink-0" />
        <span className="text-white text-xs font-medium truncate flex-1">
          {firstName}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-white absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // State D: PENDING/OPEN (Posted to Job Board) - Amber/Yellow
  if (status === 'pending' || status === 'open' || status === 'OPEN' || status === 'PUBLISHED') {
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-open"
        className={cn(
          "shift-block shift-block-open",
          "w-full h-full rounded-md",
          "bg-amber-500/90 dark:bg-amber-600/90",
          "cursor-pointer hover:bg-amber-500 dark:hover:bg-amber-600 transition-colors",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden"
        )}
        style={{ minHeight: '22px' }}
      >
        <Clock className="h-3 w-3 text-white flex-shrink-0 opacity-80" />
        <span className="text-white text-xs font-medium truncate flex-1">
          {shiftLabel}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-white absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // State E: CONFIRMED (Locked) - Green with staff name
  if (status === 'confirmed' || status === 'filled') {
    const staffName = assignedStaff?.name || assignedStaff?.displayName || 'Confirmed';
    const firstName = staffName.split(' ')[0];

    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-confirmed"
        className={cn(
          "shift-block shift-block-confirmed",
          "w-full h-full rounded-md",
          "bg-emerald-600 dark:bg-emerald-700",
          "cursor-pointer hover:bg-emerald-700 dark:hover:bg-emerald-800 transition-colors",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden"
        )}
        style={{ minHeight: '22px' }}
      >
        <div className="w-4 h-4 rounded-full bg-white/20 flex items-center justify-center flex-shrink-0">
          <span className="text-[10px] text-white font-bold">
            {firstName.charAt(0).toUpperCase()}
          </span>
        </div>
        <span className="text-white text-xs font-medium truncate flex-1">
          {firstName}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-white absolute top-0.5 right-0.5 opacity-70" />
        )}
      </div>
    );
  }

  // Fallback: Default rendering for other statuses (past, etc.)
  return (
    <div
      onClick={handleClick}
      className={cn(
        "shift-block shift-block-default",
        "w-full h-full rounded-md",
        "bg-slate-400/80 dark:bg-slate-600/80",
        "cursor-pointer hover:bg-slate-500 dark:hover:bg-slate-700 transition-colors",
        "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
        "text-white text-xs font-medium"
      )}
      style={{ minHeight: '22px' }}
    >
      <span className="truncate">{shiftLabel}</span>
      {showRecurring && (
        <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-70" />
      )}
    </div>
  );
}

