import { format } from 'date-fns';
import { Loader2, UserPlus, Repeat, Clock } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';

export interface ShiftBlockProps {
  event: {
    id: string;
    title: string;
    start: Date;
    end: Date;
    resource?: {
      booking?: any;
      status?: 'draft' | 'invited' | 'confirmed' | 'pending' | 'completed' | 'past' | 'unassigned' | 'open' | 'OPEN' | 'PUBLISHED' | 'filled';
      type?: 'job' | 'shift' | 'auto-slot' | 'bucket';
      isAutoGenerated?: boolean;
    };
  };
  onClick?: () => void;
  isRecurring?: boolean;
  /** Optional className to override or extend default styles */
  className?: string;
}

/** Normalize assignedStaff to array (supports legacy single object). */
function toAssignedList(val: unknown): Array<{ id?: string; name?: string; displayName?: string; avatarUrl?: string }> {
  if (Array.isArray(val)) return val.filter(Boolean);
  if (val && typeof val === 'object') return [val as any];
  return [];
}

/**
 * Get a clean, short display name for the shift
 * Prioritizes showing time range or simple label over long names
 */
function getShiftLabel(event: ShiftBlockProps['event']): string {
  // Try to get the time range as a compact label
  try {
    const startTime = format(event.start, 'h:mma').toLowerCase();
    return `${startTime}`;
  } catch {
    // Fallback to a simple label based on time of day
    const hour = event.start.getHours();
    if (hour < 12) return 'Morning';
    if (hour < 17) return 'Afternoon';
    return 'Evening';
  }
}

/**
 * ShiftBlock Component – Premium B2B visual design
 *
 * Status cues via slim left-border accents:
 * - Confirmed: emerald-500 left-border on dark emerald bg
 * - Pending/Open: amber-500 left-border with subtle glow
 * - Invited: orange left-border with spinner
 * - Draft: zinc border, ghosted
 * - Past: zinc-600 muted
 *
 * All blocks use rounded-xl, smooth hover scale, and touch-friendly sizing.
 */
export function ShiftBlock({ event, onClick, isRecurring, className }: ShiftBlockProps) {
  const status = event.resource?.status || 'draft';
  const shift = event.resource?.booking?.shift || event.resource?.booking?.job;
  const rawAssigned = shift?.assignedStaff ?? shift?.assignments ?? shift?.professional;
  const assignedList = toAssignedList(rawAssigned);
  const capacity = Math.max(1, (shift?.capacity ?? 1) as number);
  const filled = assignedList.length;
  const showRecurring = isRecurring || shift?.isRecurring || shift?.recurringSeriesId;
  const isAutoGenerated = event.resource?.isAutoGenerated;
  const isUnassigned = status === 'unassigned' && isAutoGenerated;
  const hasSlots = capacity > filled;

  const shiftLabel = getShiftLabel(event);

  // Handle click with proper event handling
  const handleClick = (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent event bubbling
    if (onClick) {
      onClick();
    }
  };

  // State A: UNASSIGNED (Auto-generated slot) – amber left-border accent
  if (isUnassigned) {
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-unassigned-slot"
        className={cn(
          "shift-block shift-block-unassigned",
          "w-full h-full rounded-lg min-h-[44px] min-[1024px]:min-h-[36px]",
          "bg-amber-500/15 dark:bg-amber-500/10 cursor-pointer",
          "border border-amber-500/20 dark:border-amber-500/15 border-l-[3px] border-l-amber-500",
          "flex items-center gap-1.5 px-2 py-1",
          "hover:bg-amber-500/25 dark:hover:bg-amber-500/20",
          "transition-all duration-200 ease-out",
          "text-amber-700 dark:text-amber-400 relative overflow-hidden",
          className
        )}
        /* 44px touch target on mobile, relaxed on desktop */
      >
        <Clock className="h-3.5 w-3.5 flex-shrink-0 opacity-80" />
        <span className="text-xs font-semibold truncate">{shiftLabel}</span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-60" />
        )}
      </div>
    );
  }

  // State B: DRAFT (Ghost Slot) – zinc ghosted style
  if (status === 'draft') {
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-ghost-slot"
        className={cn(
          "shift-block shift-block-draft",
          "w-full h-full rounded-lg border min-h-[44px] min-[1024px]:min-h-[36px]",
          "bg-zinc-100/50 dark:bg-zinc-800/30 cursor-pointer",
          "border-zinc-300/60 dark:border-zinc-700/50",
          "border-l-[3px] border-l-zinc-400 dark:border-l-zinc-500",
          "flex items-center gap-1.5 px-2 py-1.5",
          "hover:bg-zinc-200/60 dark:hover:bg-zinc-700/40",
          "transition-all duration-200 ease-out",
          "text-zinc-500 dark:text-zinc-400 relative overflow-hidden",
          className
        )}
        /* 44px touch target on mobile, relaxed on desktop */
      >
        <UserPlus className="h-3.5 w-3.5 flex-shrink-0 opacity-60" />
        <span className="text-xs font-semibold truncate">Open</span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-50" />
        )}
      </div>
    );
  }

  // State C: INVITED (Pending) – orange left-border with spinner
  if (status === 'invited') {
    const first = assignedList[0];
    const staffName = first?.name || first?.displayName || 'Pending';
    const firstName = staffName.split(' ')[0];

    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-pending"
        className={cn(
          "shift-block shift-block-invited",
          "w-full h-full rounded-lg min-h-[44px] min-[1024px]:min-h-[36px]",
          "bg-orange-500/15 dark:bg-orange-500/10",
          "border border-orange-500/20 dark:border-orange-500/15 border-l-[3px] border-l-orange-500",
          "cursor-pointer hover:bg-orange-500/25 dark:hover:bg-orange-500/20",
          "transition-all duration-200 ease-out",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
          className
        )}
        /* 44px touch target on mobile, relaxed on desktop */
      >
        <Loader2 className="h-3.5 w-3.5 text-orange-500 dark:text-orange-400 animate-spin flex-shrink-0" />
        <span className="text-orange-700 dark:text-orange-300 text-xs font-semibold truncate flex-1">
          {capacity > 1 ? `${filled}/${capacity} Filled` : firstName}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-orange-500/60 absolute top-0.5 right-0.5" />
        )}
      </div>
    );
  }

  // State D: PENDING/OPEN (Posted to Job Board) – amber glow accent
  if (status === 'pending' || status === 'open' || status === 'OPEN' || status === 'PUBLISHED') {
    const openLabel = capacity > 1 ? `0/${capacity}` : shiftLabel;
    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-open"
        className={cn(
          "shift-block shift-block-open",
          "w-full h-full rounded-lg min-h-[44px] min-[1024px]:min-h-[36px]",
          "bg-amber-500/15 dark:bg-amber-500/10",
          "border border-amber-500/20 dark:border-amber-500/15 border-l-[3px] border-l-amber-500",
          "cursor-pointer hover:bg-amber-500/25 dark:hover:bg-amber-500/20",
          "transition-all duration-200 ease-out",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
          "shadow-[0_0_8px_rgba(245,158,11,0.08)] dark:shadow-[0_0_12px_rgba(245,158,11,0.12)]",
          className
        )}
        /* 44px touch target on mobile, relaxed on desktop */
      >
        <Clock className="h-3.5 w-3.5 text-amber-600 dark:text-amber-400 flex-shrink-0 opacity-80" />
        <span className="text-amber-700 dark:text-amber-300 text-xs font-semibold truncate flex-1">
          {openLabel}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-amber-500/60 absolute top-0.5 right-0.5" />
        )}
      </div>
    );
  }

  // State E: CONFIRMED (Locked) – emerald left-border, dark emerald bg
  if (status === 'confirmed' || status === 'filled') {
    const avatarsToShow = assignedList.slice(0, 3);
    const first = assignedList[0];
    const firstName = (first?.name || first?.displayName || 'Confirmed').split(' ')[0];

    return (
      <div
        onClick={handleClick}
        data-testid="shift-block-confirmed"
        className={cn(
          "shift-block shift-block-confirmed",
          "w-full h-full rounded-lg min-h-[44px] min-[1024px]:min-h-[36px]",
          "bg-emerald-500/15 dark:bg-emerald-500/10",
          "border border-emerald-500/20 dark:border-emerald-500/15 border-l-[3px] border-l-emerald-500",
          "cursor-pointer hover:bg-emerald-500/25 dark:hover:bg-emerald-500/20",
          "transition-all duration-200 ease-out",
          "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
          className
        )}
        /* 44px touch target on mobile, relaxed on desktop */
      >
        <div className="flex items-center gap-0.5 flex-shrink-0">
          {avatarsToShow.map((s, i) => (
            <Avatar key={s?.id || i} className="h-4 w-4 border border-emerald-500/30">
              <AvatarImage src={(s as any)?.avatarUrl} />
              <AvatarFallback className="text-[8px] bg-emerald-500/20 text-emerald-700 dark:text-emerald-300">
                {(s?.name || s?.displayName || '?').charAt(0).toUpperCase()}
              </AvatarFallback>
            </Avatar>
          ))}
          {hasSlots && (
            <div
              className="h-4 w-4 rounded-full border border-dashed border-emerald-500/50 flex items-center justify-center bg-emerald-500/10"
              title="Add Worker"
            >
              <UserPlus className="h-2.5 w-2.5 text-emerald-600 dark:text-emerald-400" />
            </div>
          )}
        </div>
        <span className="text-emerald-700 dark:text-emerald-300 text-xs font-semibold truncate flex-1">
          {capacity > 1 ? `${filled}/${capacity} Filled` : firstName}
        </span>
        {showRecurring && (
          <Repeat className="h-2.5 w-2.5 text-emerald-500/60 absolute top-0.5 right-0.5" />
        )}
      </div>
    );
  }

  // Fallback: Default rendering for other statuses (past, completed, etc.) – muted zinc
  return (
    <div
      onClick={handleClick}
      className={cn(
        "shift-block shift-block-default",
        "w-full h-full rounded-lg min-h-[44px] min-[1024px]:min-h-[36px]",
        "bg-zinc-200/50 dark:bg-zinc-800/40",
        "border border-zinc-300/40 dark:border-zinc-700/30 border-l-[3px] border-l-zinc-400 dark:border-l-zinc-600",
        "cursor-pointer hover:bg-zinc-300/50 dark:hover:bg-zinc-700/40",
        "transition-all duration-200 ease-out",
        "flex items-center gap-1.5 px-2 py-1 relative overflow-hidden",
        "text-zinc-600 dark:text-zinc-400 text-xs font-semibold",
        className
      )}
      style={{ minHeight: '36px' }}
    >
      <span className="truncate">{shiftLabel}</span>
      {showRecurring && (
        <Repeat className="h-2.5 w-2.5 absolute top-0.5 right-0.5 opacity-50" />
      )}
    </div>
  );
}
