name: E2E (Cypress)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build client
        run: npm run build

      - name: Run Cypress E2E (mobile overflow + routing)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run start:ci
          wait-on: 'http://localhost:5000/health'
          wait-on-timeout: 240
          config: defaultCommandTimeout=20000,requestTimeout=20000,responseTimeout=20000,pageLoadTimeout=60000,retries=2
          spec: cypress/e2e/10-routing-authentication-working.cy.ts
        env:
          E2E_TEST: '1'
          E2E_TEST_KEY: 'test'
          VITE_E2E: '1'

      - name: Upload screenshots (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos


